### ISSUE TITLE
Kevinbmxisaac

### ISSUE THREAD

**Issue by kevinbmx50** [MicrosoftDocs/AdaptiveCards#304] opened 2020-07-14 07:31 UTC
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "Here is a ninja cat"
        },
        {
            "type": "Image",
            "url": "http://adaptivecards.io/content/cats/1.png"
        }
    ]
}

**Comment by matthidinger** [comment] 2020-07-14 15:52
Dupe of #306

**Closed by matthidinger** 2020-07-14 15:52 UTC
Labels: Pri3
