### ISSUE TITLE
Kevin Ochoa 

### ISSUE THREAD

**Issue by kevinbmx50** [MicrosoftDocs/AdaptiveCards#305] opened 2020-07-14 07:42 UTC
> Kevin Ubaldo Ochoa quinonez 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 272125ec-d694-2abd-a879-d288f3d28934
* Version Independent ID: e5c34866-d43c-a204-f03c-677c5a646efe
* Content: [Getting Started - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/getting-started)
* Content Source: [AdaptiveCards/authoring-cards/getting-started.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/authoring-cards/getting-started.md)
* Product: **adaptive-cards**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "Here is a ninja cat"
        },
        {
            "type": "Image",
            "url": "http://adaptivecards.io/content/cats/1.png"
        }
    ]
}

>

**Comment by matthidinger** [comment] 2020-07-14 15:51
Dupe of #306

**Closed by matthidinger** 2020-07-14 15:51 UTC
Labels: Pri2, adaptive-cards/prod
