### ISSUE TITLE
Perpetually "Coming Soon"???

### ISSUE THREAD

**Issue by dan-meier** [MicrosoftDocs/AdaptiveCards#58] opened 2018-04-27 02:18 UTC
This page has said "Coming soon" for nearly a year.  PLEASE create the documentation soon!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e7e2a4e-06c9-135b-d6eb-94f69d6c06b8
* Version Independent ID: d3eb5fdf-cac3-28fa-3d32-127455a8726a
* Content: [Xamarin.Forms SDK - Adaptive Cards](https://docs.microsoft.com/en-us/adaptive-cards/display/libraries/xamarinforms)
* Content Source: [AdaptiveCards/display/libraries/XamarinForms.md](https://github.com/MicrosoftDocs/AdaptiveCards/blob/master/AdaptiveCards/display/libraries/XamarinForms.md)
* Service: **unspecified**
* GitHub Login: @matthidinger
* Microsoft Alias: **mahiding**

**Comment by matthidinger** [comment] 2018-04-30 16:57
Hi @dan-meier, thanks for your patience while we bootstrap the SDKs. We're actively making progress on Xamarin but it's not quite ready to release yet. You can use this PR to get early access or to provide feedback.

 https://github.com/Microsoft/AdaptiveCards/pull/1305

**Comment by anbare** [comment] 2018-06-25 17:39
Closing as dupe of #67

**Closed by anbare** 2018-06-25 17:39 UTC
