### ISSUE TITLE
Two bugs in the repeat method.

### ISSUE THREAD

**Issue by shikshik** [MicrosoftDocs/AdaptiveCards#251] opened 2020-01-30 08:29 UTC
I think I found two bugs in the repeat method.

1. When adding a condition inside items in repeating items, the condition only checks the first item value for all other items.

For example:
`"items": [
"type": "TextBlock",
"text": "{if(numericValue >= 0, 'good', 'attention')}
]`

If the first item is less than 0, all other items will be treated as this condition is false regardless of their own values.
I changed the first item value and noticed all others are affected by it. It does display the right value for each item (even when printing next to the "if" condition.

2. When I try to print a numeric value by itself, it does not display it unless I've added some string or space next to it:

`"text": "{numericValue}"` -> will result in display nothing.
`"text": "{numericValue} "` -> will result in displaying the value with a space (or any other character).

Both bugs are reproducible in https://adaptivecards.io/designer/ as well in a real code test I did.

_Originally posted by @shikshik in https://github.com/MicrosoftDocs/AdaptiveCards/issues/211#issuecomment-579678070_

**Comment by matthidinger** [comment] 2020-01-31 02:04
Thanks for reporting this!

**Comment by dclaux** [comment] 2020-01-31 04:02
@shikshik thanks for reporting. It would be great to have a card + data payload to easily repro.

That said, I think I have already fixed this issue in the `js/renderer-refactor` branch with this commit: https://github.com/microsoft/AdaptiveCards/commit/3a0e720536498a419dc0d2e9dce928e2cea9dd32

If you feel like giving it a shot...

**Comment by shikshik** [comment] 2020-02-03 08:54
@dclaux thanks for the fast reply!
I did a test for your PR via the link mentioned in the PR itself (https://adaptivecardsci.z5.web.core.windows.net/pr/3508/designer/?preview=1).

It is actually worse than it was :/
The repeat is now repeating the same first object 3 times instead of showing the entire data:
![image](https://user-images.githubusercontent.com/6535924/73637874-ec6c7100-4671-11ea-87fd-44c7c2635034.png)

Live designer:
![image](https://user-images.githubusercontent.com/6535924/73637905-fe4e1400-4671-11ea-925d-aa305271a652.png)

I've created a sample for you to test, it also includes a conditional coloring (which I also removed in my tests to see if it affects the repeat somehow).
I also compared the same data and structure with the live version of the designer.

Data:
`[
  {
    "name": "Object-1",
    "lastPrice": 1.10762,
    "changePriceRatio": -0.17
  },
  {
    "name": "Object-2",
    "lastPrice": 1578.205,
    "changePriceRatio": -0.68
  },
  {
    "name": "Object-3",
    "lastPrice": 51.475,
    "changePriceRatio": -0.23
  },
  {
    "name": "Object-4",
    "lastPrice": 28324,
    "changePriceRatio": 0.35
  },
  {
    "name": "Object-5",
    "lastPrice": 9338.87,
    "changePriceRatio": -1.04
  }
]`

Structure:
`{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "Container",
      "items": [
        {
          "type": "ColumnSet",
          "columns": [
            {
              "type": "Column",
              "width": "auto",
              "items": [
                {
                  "type": "TextBlock",
                  "text": "{if(changePriceRatio >= 0, '▲', '▼')}",
                  "color": "{if(changePriceRatio >= 0, 'good', 'attention')}"
                }
              ]
            },
            {
              "type": "Column",
              "width": "stretch",
              "items": [
                {
                  "type": "TextBlock",
                  "text": "{name}"
                }
              ]
            },
            {
              "type": "Column",
              "width": "stretch",
              "items": [
                {
                  "type": "TextBlock",
                  "text": "{lastPrice} ",
                  "horizontalAlignment": "Center"
                }
              ],
              "horizontalAlignment": "Center"
            },
            {
              "type": "Column",
              "width": "auto",
              "items": [
                {
                  "type": "TextBlock",
                  "text": "{changePriceRatio}%",
                  "color": "{if(changePriceRatio >= 0, 'good', 'attention')}"
                }
              ],
              "horizontalAlignment": "Right"
            }
          ]
        }
      ],
      "$data": "{$root}"
    }
  ]
}
`

Btw, color with a conditional phrase, return an error in the designer when parsing "Invalid "color" value", but it does work in the preview.

As for the second issue, I tried `"text": "{toString(numericValue)}"` which does not work on either version of the designer.

Let me know if I've should be tested it locally instead.

**Comment by shikshik** [comment] 2020-02-10 08:19
Hey @dclaux , any updates regarding the bugs? Did you manage to reproduce?
If those are not going to be fixed soon I will apply some workarounds in the meanwhile, would be nice to know if it is planned to be fixed in the next release.

Thanks!

**Comment by dclaux** [comment] 2020-02-10 20:14
Hey @shikshik I am sorry for the delay, somehow I missed your reply and only noticed it today a few moments ago.

I am not able to repro the problem with the card and data payloads you included. End result for me is this:
![image](https://user-images.githubusercontent.com/1334689/74185431-7e89f180-4bfd-11ea-902f-2dd1a8285790.png)

The bug I was saying should be fixed should have been fixed with [this commit](https://github.com/microsoft/AdaptiveCards/pull/3508/commits/3a0e720536498a419dc0d2e9dce928e2cea9dd32) 19 days ago. For the second issue, I didn't say `toString` was available, I said it was an option we were considering and I asked for your opinion.

Since then [I actually did add `toString`](https://github.com/microsoft/AdaptiveCards/pull/3508/commits/49ee3d531c766b21343a558a919ddfa5c24bcd54), so it is now available in `js/renderer-refactor`. You may want to take another look.

It is expected for the designer to emit a warning about `color` (or other enumeration properties for that matter) when its value is an expression. This behavior may be enhanced in a later release.

**Comment by dclaux** [comment] 2020-02-10 20:22
Oh, and indeed you will need to test locally. It doesn't seem that the bits at https://adaptivecardsci.z5.web.core.windows.net/pr/3508/designer/?preview=1 are getting updated anymore (I don't know why that is, @matthidinger do you have an idea?)

**Comment by shikshik** [comment] 2020-02-11 08:59
Hey, thanks!
I will test this branch locally today.
Regarding `toString`, I'm sorry, probably misunderstood. This solution is great to have, but I think the solution should be transparent to the end-user, so nothing should be added to print out values such as this. I understand it is hard to solve, so I guess using an additional function to convert types is ok.

Btw, when is this branch planned to be merged?

**Comment by shikshik** [comment] 2020-02-11 11:46
@dclaux , I couldn't manage to test since I had to build it locally and got an error when tried to build:

src/card-elements.ts:2241:12 - error TS2322: Type 'null' is not assignable to type '(sender: Media) => void'.

2241     static onPlay: (sender: Media) => void = null;

Seems like you recently added it by a request to fix angular build (https://github.com/microsoft/AdaptiveCards/issues/3736).

If there is a way to test a pre-built version of the branch, that will be great.

Thanks.

**Comment by jarusse** [comment] 2020-02-21 11:39
Hey folks,

Just wanted to chime in to say I'm having the same problems as @shikshik precisely.
When I use the PR link I also get the same extra issue of it not even looping through the data.

@dclaux - are you saying you're unable to repro even in the web designer tool?

**Comment by dclaux** [comment] 2020-02-21 17:06
@shikshik as you figured the error you are seeing was introduced [by this PR](https://github.com/microsoft/AdaptiveCards/pull/3737), and it happens because in the **js/renderer-refactor** branch, the library is now compiled with the `strictNullCheck` and `noImplicitAny` compiler directives. I've fixed it by changing the declaration of the `onPlay` event to
```typescript
static onPlay?: (sender: Media) => void;
```
Please try compiling locally again. I just tested again on my end, and I am not able to repro.

Interestingly though, the site at https://adaptivecardsci.z5.web.core.windows.net/pr/3508/designer/?preview=1 has been updated but the problem isn't fixed there. I have no idea why, but bottom line please test on a local build for now.

**Comment by dclaux** [comment] 2020-02-21 17:07
@jarusse I am not able to repro this on a local build of the **js/renderer-refactor** branch.

**Comment by shikshik** [comment] 2020-02-24 11:28
@dclaux , I tried again with the latest fix you did, still cannot build properly. I'm getting issues with webpack loaders:

```
ERROR in ./src/card-object.ts 10:13
Module parse failed: Unexpected token (10:13)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

export class ValidationResults {
      readonly allIds: Dictionary<number> = {}; // In This line
      readonly validationEvents: IValidationEvent[] = []; 

@ ./src/adaptivecards.ts 5:0-30 5:0-30
```
The build fails in other several places for the same reason.

Just to make clear what I did:
1. Installed node modules in the parent directory (since first try to build returned I'm missing "html-webpack-plugin").
2. Installed node modules for adaptivecards.
3. Run build command (or release).

Did I miss anything?

**Comment by matthidinger** [comment] 2020-03-20 18:10
Hi folks, this should be fixed in the `adaptivecards-templating` npm package version 0.1.1-alpha.1
It's also fixed on https://adaptivecards.io/designer (make sure the clear your cache in case any scripts are stored in the browser)

Please let us know if you have any troubles!

**Comment by shikshik** [comment] 2020-03-23 08:39
@matthidinger , thanks for the update, I just tested it locally and the repeat issue is now looking good!

Thanks for fixing this bug!

**Comment by taerimhan** [comment] 2020-04-11 14:11
@matthidinger, will there be nuget package update for this repeat issue as well? Having the same problem as shikshik using .NET SDK (AdaptiveCards.Templating --version 0.1.0-alpha1).

**Comment by matthidinger** [comment] 2020-04-21 15:22
Hi @taerimhan, we're working on a major .NET (and JS) templating update in the next few weeks. Stay tuned and thank you for your patienec!

**Comment by taerimhan** [comment] 2020-04-22 21:39
@matthidinger thank you for the update! Looking forward to it :)

**Comment by matthidinger** [comment] 2020-07-08 16:10
These should be fixes in the latest v1..0 releases for .NET and JS :) Please reopen and/or let us know if you have any further issues!

**Closed by matthidinger** 2020-07-08 16:10 UTC
Labels: Pri3
